name: Deploy image to Docker and Nginx

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t rabbani676/deploy-this-to-docker-and-nginx:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker tag rabbani676/deploy-this-to-docker-and-nginx:latest rabbani676/deploy-this-to-docker-and-nginx:latest
        docker push rabbani676/deploy-this-to-docker-and-nginx:latest
