name: Deploy to Docker and Nginx

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t deploy-this-to-docker-and-nginx:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker tag deploy-this-to-docker-and-nginx:latest ${{ secrets.DOCKER_USERNAME }}/deploy-this-to-docker-and-nginx:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/deploy-this-to-docker-and-nginx:latest

    - name: Deploy Docker container
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/deploy-this-to-docker-and-nginx:latest
        docker stop deploy-this-to-docker-and-nginx || true
        docker rm deploy-this-to-docker-and-nginx || true
        docker run -d --name deploy-this-to-docker-and-nginx -p 80:80 ${{ secrets.DOCKER_USERNAME }}/deploy-this-to-docker-and-nginx:latest

    - name: Configure Nginx
      run: |
        docker exec -it my-nginx-container bash -c 'echo "server { listen 80; location / { proxy_pass http://deploy-this-to-docker-and-nginx:80; } }" > /etc/nginx/conf.d/default.conf'
        docker exec -it my-nginx-container nginx -s reload
