name: Deploy Frontend and Backend to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout frontend code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image for frontend
      run: |
        cd frontend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-deploy:latest .

    - name: Push Docker image for frontend to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend-deploy:latest

  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout backend code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image for backend
      run: |
        cd backend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-deploy:latest .

    - name: Push Docker image for backend to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/backend-deploy:latest
