name: Python Docker CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_IMAGE: musawar96/workflow
  DEPLOY_SERVER: user@server
  SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: mazzyy/git-actions-playground
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main

    - name: Build Docker image
      run: |
        ls -la  # List files to verify Dockerfile exists
        docker build -t ${{ env.DOCKER_IMAGE }} .  # Ensure the Dockerfile is in the root or specify the correct path

    - name: Run Docker container
      run: |
        docker run --name workflow-container -d ${{ env.DOCKER_IMAGE }}
        sleep 5  # Wait for container to start

    - name: Check Docker container output
      run: |
        docker logs workflow-container
    
    - name: Stop and remove Docker container
      run: |
        docker stop workflow-container
        docker rm workflow-container

  deploy-docker-image:
    runs-on: ubuntu-latest
    needs: build-and-test
    name: Deploy Docker Image

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: musawar96/git-actions-playground
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main

    - name: Deploy Docker image
      run: |
        docker tag ${{ env.DOCKER_IMAGE 
