create git action to comment on issue 
```yaml
name: Issue Comment
on:
  issue_comment:
    types: [created]
jobs:

  issue_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on Issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
           This is a multi-line test comment
          - With GitHub **Markdown** :sparkles:
          - Created by [create-or-update-comment] [1]