name: Create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "Dump GitHub context"
        run: |
          echo '${{ toJSON(github.event) }}' | jq .

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number:  ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - With a task list
              - [x] Item 1
              - [ ] Item 2

            
          reactions: '+1'


  comment-with-gh-api:
    runs-on: ubuntu-latest
    steps:
      - name: "Comment with API"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.organization.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          gh api -X POST \
            "https://api.github.com/repos/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments" \
            -f "body='This is a comment from the GitHub API with a task list\n- [x] Item 1\n- [ ] Item 2'"

     

          
          
   
